#################
# Ritik Kumar Singh (AM.EN.U4CSE20061)
# CSE A Batch 2020
# Lab Assignment 1 (Meteor-landings)
#################

In [5]:
import numpy as np
import pandas as pd
df = pd.read_csv("C:/Users/ritik/Jupyter Notebooks/DataSets/meteorite-landings.csv")

In [6]:
####### QUES 2
df.shape

(45716, 10)

In [7]:
####### QUES 3
df['year'].describe()

count    45428.000000
mean      1991.772189
std         27.181247
min        301.000000
25%       1987.000000
50%       1998.000000
75%       2003.000000
max       2501.000000
Name: year, dtype: float64

In [8]:
####### QUES 4a
new_df1 = df[(df['year'] < 860) | (df['year'] > 2016)]
new_df1

name     id nametype           recclass   mass   fall  \
16356                 Havana  11857    Valid  Iron, IAB complex    NaN  Found   
30679  Northwest Africa 7701  57150    Valid                CK6   55.0  Found   
38188                     Ur  24125    Valid               Iron    NaN  Found   
38301        Wietrzno-Bobrka  24259    Valid               Iron  376.0  Found   

         year    reclat   reclong              GeoLocation  
16356   301.0  40.33333 -90.05000  (40.333330, -90.050000)  
30679  2101.0   0.00000   0.00000     (0.000000, 0.000000)  
38188  2501.0  30.90000  46.01667   (30.900000, 46.016670)  
38301   601.0  49.41667  21.70000   (49.416670, 21.700000)

In [9]:
####### QUES 4b
new_df2 = df[(df['reclong'] <= 180) & (df['reclong'] >= -180)]
new_df2


name     id nametype              recclass      mass   fall  \
0          Aachen      1    Valid                    L5      21.0   Fell   
1          Aarhus      2    Valid                    H6     720.0   Fell   
2            Abee      6    Valid                   EH4  107000.0   Fell   
3        Acapulco     10    Valid           Acapulcoite    1914.0   Fell   
4         Achiras    370    Valid                    L6     780.0   Fell   
...           ...    ...      ...                   ...       ...    ...   
45711  Zillah 002  31356    Valid               Eucrite     172.0  Found   
45712      Zinder  30409    Valid  Pallasite, ungrouped      46.0  Found   
45713        Zlin  30410    Valid                    H4       3.3  Found   
45714   Zubkovsky  31357    Valid                    L6    2167.0  Found   
45715  Zulu Queen  30414    Valid                  L3.7     200.0  Found   

         year    reclat    reclong               GeoLocation  
0      1880.0  50.77500    6.08333     (50.775000, 6.083330)  
1      1951.0  56.18333   10.23333    (56.183330, 10.233330)  
2      1952.0  54.21667 -113.00000  (54.216670, -113.000000)  
3      1976.0  16.88333  -99.90000   (16.883330, -99.900000)  
4      1902.0 -33.16667  -64.95000  (-33.166670, -64.950000)  
...       ...       ...        ...                       ...  
45711  1990.0  29.03700   17.01850    (29.037000, 17.018500)  
45712  1999.0  13.78333    8.96667     (13.783330, 8.966670)  
45713  1939.0  49.25000   17.66667    (49.250000, 17.666670)  
45714  2003.0  49.78917   41.50460    (49.789170, 41.504600)  
45715  1976.0  33.98333 -115.68333  (33.983330, -115.683330)  

[38400 rows x 10 columns]

In [10]:
####### QUES 4c
new_df3 = new_df2[(new_df2['reclat']== 0) | (new_df2['reclong'] == 0)]
new_df3

name     id nametype   recclass     mass   fall  \
37     Northwest Africa 5815  50693    Valid         L5   256.80  Found   
596              Mason Gully  53653    Valid         H5    24.54   Fell   
610                     Meru  15491    Valid        LL6  6000.00   Fell   
1648       Allan Hills 09004  52119    Valid  Howardite   221.70  Found   
1649       Allan Hills 09005  55797    Valid         L5   122.30  Found   
...                      ...    ...      ...        ...      ...    ...   
45655          Yamato 984144  40764    Valid         H6    37.44  Found   
45656          Yamato 984145  40765    Valid         L6    54.80  Found   
45657          Yamato 984146  40766    Valid         H3    19.32  Found   
45658          Yamato 984147  40767    Valid        LL6   118.90  Found   
45659          Yamato 984148  40768    Valid         L5     4.59  Found   

         year  reclat   reclong            GeoLocation  
37        NaN     0.0   0.00000   (0.000000, 0.000000)  
596    2010.0     0.0   0.00000   (0.000000, 0.000000)  
610    1945.0     0.0  37.66667  (0.000000, 37.666670)  
1648   2009.0     0.0   0.00000   (0.000000, 0.000000)  
1649   2009.0     0.0   0.00000   (0.000000, 0.000000)  
...       ...     ...       ...                    ...  
45655  1998.0     0.0   0.00000   (0.000000, 0.000000)  
45656  1998.0     0.0   0.00000   (0.000000, 0.000000)  
45657  1998.0     0.0   0.00000   (0.000000, 0.000000)  
45658  1998.0     0.0   0.00000   (0.000000, 0.000000)  
45659  1998.0     0.0   0.00000   (0.000000, 0.000000)  

[6438 rows x 10 columns]

In [11]:
####### QUES 5
new_df3.isnull().values.any()

True

In [12]:
####### QUES 6
new_df4 = df[df['mass'].isnull()]
new_df4

name     id nametype      recclass  mass   fall    year  \
12       Aire-sur-la-Lys    425    Valid       Unknown   NaN   Fell  1769.0   
38                Angers   2301    Valid            L6   NaN   Fell  1822.0   
76     Barcelona (stone)   4944    Valid            OC   NaN   Fell  1704.0   
93              Belville   5009    Valid            OC   NaN   Fell  1937.0   
172    Castel Berardenga   5292    Valid    Stone-uncl   NaN   Fell  1791.0   
...                  ...    ...      ...           ...   ...    ...     ...   
38275     Wei-hui-fu (a)  24231    Valid          Iron   NaN  Found  1931.0   
38276     Wei-hui-fu (b)  24232    Valid          Iron   NaN  Found  1931.0   
38278            Weiyuan  24233    Valid  Mesosiderite   NaN  Found  1978.0   
41460      Yamato 792768  28117    Valid           CM2   NaN  Found  1979.0   
45698      Zapata County  30393    Valid          Iron   NaN  Found  1930.0   

         reclat    reclong               GeoLocation  
12     50.66667    2.33333     (50.666670, 2.333330)  
38     47.46667   -0.55000    (47.466670, -0.550000)  
76     41.36667    2.16667     (41.366670, 2.166670)  
93    -32.33333  -64.86667  (-32.333330, -64.866670)  
172    43.35000   11.50000    (43.350000, 11.500000)  
...         ...        ...                       ...  
38275       NaN        NaN                       NaN  
38276       NaN        NaN                       NaN  
38278  35.26667  104.31667   (35.266670, 104.316670)  
41460 -71.50000   35.66667   (-71.500000, 35.666670)  
45698  27.00000  -99.00000   (27.000000, -99.000000)  

[131 rows x 10 columns]

In [13]:
####### QUES 7
correct_lat_long_df = df
print(correct_lat_long_df['mass'].describe())

count    4.558500e+04
mean     1.327808e+04
std      5.749889e+05
min      0.000000e+00
25%      7.200000e+00
50%      3.260000e+01
75%      2.026000e+02
max      6.000000e+07
Name: mass, dtype: float64


In [14]:
####### QUES 8
arr = np.array(new_df4.index)
arr

array([   12,    38,    76,    93,   172,   204,   262,   308,   312,
         320,   324,   346,   392,   561,   577,   644,   664,   678,
         692,   709,   729,   747,   751,   773,   785,   791,   865,
         953,  1014,  1040,  1051,  1076,  3440,  3452,  5044,  5045,
        5123,  5182,  5242,  5268,  5432,  5468,  5479,  5583,  5693,
        5694,  6844,  6876,  9168,  9217, 12536, 12539, 12595, 15938,
       15943, 15944, 15959, 16356, 16367, 16368, 16403, 16472, 16547,
       17249, 17273, 17341, 17363, 17391, 17462, 19720, 22946, 26270,
       26398, 28736, 31013, 31014, 31015, 31016, 31017, 31018, 31019,
       31020, 31021, 31022, 31023, 31024, 31025, 31026, 31027, 31028,
       31029, 31030, 31031, 31032, 31033, 31034, 31035, 31036, 31037,
       31038, 31039, 31040, 31041, 31042, 31043, 31044, 31045, 31046,
       31047, 31048, 31049, 31050, 31051, 31052, 31053, 31054, 31055,
       31056, 31057, 31058, 31059, 31097, 31141, 31146, 36812, 38188,
       38275, 38276,

In [15]:
####### QUES 9
new_df4['mass']

12      NaN
38      NaN
76      NaN
93      NaN
172     NaN
         ..
38275   NaN
38276   NaN
38278   NaN
41460   NaN
45698   NaN
Name: mass, Length: 131, dtype: float64

In [16]:
X = df['mass'].median()

In [17]:
####### QUES 10
df['mass']=df['mass'].fillna(df['mass'].median())

In [18]:
####### QUES 11
df['mass'].isnull().values.any()

False

In [19]:
####### QUES 12
print(df.loc[arr,'mass'].describe())

count    1.310000e+02
mean     3.260000e+01
std      4.992892e-14
min      3.260000e+01
25%      3.260000e+01
50%      3.260000e+01
75%      3.260000e+01
max      3.260000e+01
Name: mass, dtype: float64


In [20]:
####### QUES 13
df['mass'].describe()

count    4.571600e+04
mean     1.324012e+04
std      5.741649e+05
min      0.000000e+00
25%      7.200000e+00
50%      3.260000e+01
75%      2.011000e+02
max      6.000000e+07
Name: mass, dtype: float64

In [21]:
####### QUES 14
arr9=np.arange(1,10) 
print(arr9) 
arr9.shape=(3,3) 
print(arr9) 
List=arr9.tolist() 
print(List)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
